#!/usr/bin/env python3
"""make_launcher.py — build or repair the live-source Bristol.app.

Approach A in BUILD_APP.md, as a program instead of a recipe: a minimal ``.app``
bundle whose executable is a shell script that runs this repo's ``app.py``. Run
it once and Bristol is in ``~/Applications``, ready to keep in the Dock; run it
again after moving or renaming the repo and the launcher is repointed.

The generated script resolves the repo at *launch* time from the per-machine
instance pointer (``~/Library/Application Support/BristolTickets/instance.json``,
see ``instance.py``), falling back to the path baked in when it was generated.
// A launcher that only hard-codes a path stops working the moment the repo
// folder is renamed, and the failure is silent — the Dock tile bounces once and
// nothing opens.

The bundle it writes is a per-machine artifact holding absolute paths, so it is
never committed; it lives in ``~/Applications``, outside the repo.

Usage:
    python3 src/tools/bristol/make_launcher.py            # build/repair it
    python3 src/tools/bristol/make_launcher.py --where    # print its location

Bristol is self-contained: this imports nothing from the rest of ``src/tools/``.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import stat
import subprocess
import sys
from pathlib import Path

APP_NAME = "Bristol"
HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[2]          # src/tools/bristol -> src/tools -> src -> repo


def app_path() -> Path:
    """Where the launcher bundle lives: the user's own Applications folder, which
    needs no admin rights."""
    return Path.home() / "Applications" / f"{APP_NAME}.app"


def find_python() -> str:
    """The interpreter that actually has PySide6.

    // A Finder-launched app inherits a minimal PATH, so a bare `python3` in the
    // launcher often resolves to a system Python without PySide6 and the app
    // dies before it draws a window. The absolute path is baked in instead.
    """
    candidates = [sys.executable]
    which = shutil.which("python3")
    if which:
        candidates.append(which)
    for exe in candidates:
        if not exe:
            continue
        try:
            subprocess.run([exe, "-c", "import PySide6"], check=True,
                           capture_output=True, timeout=60)
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired, OSError):
            continue
        return exe
    sys.exit(
        "make_launcher: ERROR — no Python on this machine has PySide6.\n"
        "  Install it into the interpreter you want Bristol to use:\n"
        "      python3 -m pip install PySide6\n"
        "  then run this again with that same python3."
    )


def launcher_script(python_exe: str) -> str:
    """The bundle's executable: resolve the repo, then exec app.py."""
    return f"""#!/bin/bash
# Generated by src/tools/bristol/make_launcher.py. Regenerate; do not hand-edit.
PYBIN={json.dumps(python_exe)}
FALLBACK_ROOT={json.dumps(str(REPO_ROOT))}
POINTER="$HOME/Library/Application Support/BristolTickets/instance.json"

ROOT=""
if [ -f "$POINTER" ]; then
  ROOT=$("$PYBIN" -c 'import json,sys
try:
    print(json.load(open(sys.argv[1])).get("repo_root",""))
except Exception:
    print("")' "$POINTER" 2>/dev/null)
fi
if [ ! -f "$ROOT/src/tools/bristol/app.py" ]; then
  ROOT="$FALLBACK_ROOT"
fi
if [ ! -f "$ROOT/src/tools/bristol/app.py" ]; then
  /usr/bin/osascript -e 'display alert "Bristol cannot find its files" message "The repo has moved. Run: python3 src/tools/bristol/make_launcher.py" as critical'
  exit 1
fi
exec "$PYBIN" "$ROOT/src/tools/bristol/app.py"
"""


INFO_PLIST = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>{APP_NAME}</string>
  <key>CFBundleDisplayName</key><string>{APP_NAME}</string>
  <key>CFBundleIdentifier</key><string>local.bristol.launcher</string>
  <key>CFBundleExecutable</key><string>{APP_NAME}</string>
  <key>CFBundleIconFile</key><string>icon</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
"""


def build() -> Path:
    """Write the bundle, replacing any existing one."""
    python_exe = find_python()
    bundle = app_path()
    macos = bundle / "Contents" / "MacOS"
    resources = bundle / "Contents" / "Resources"

    if bundle.exists():
        shutil.rmtree(bundle)
    macos.mkdir(parents=True)
    resources.mkdir(parents=True)

    (bundle / "Contents" / "Info.plist").write_text(INFO_PLIST, encoding="utf-8")
    exe = macos / APP_NAME
    exe.write_text(launcher_script(python_exe), encoding="utf-8")
    exe.chmod(exe.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    icon = HERE / "icon.icns"
    if icon.exists():
        shutil.copyfile(icon, resources / "icon.icns")

    # Nudge Finder/Dock to re-read the bundle it just had replaced under it.
    subprocess.run(["/usr/bin/touch", str(bundle)], check=False)
    return bundle


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--where", action="store_true",
                        help="print where the launcher lives and exit")
    args = parser.parse_args()

    if args.where:
        print(app_path())
        return

    if sys.platform != "darwin":
        sys.exit("make_launcher: ERROR — the .app bundle is a macOS artifact.")

    bundle = build()
    print(f"OK: {bundle}")
    print(f"    runs: {REPO_ROOT}/src/tools/bristol/app.py")
    print("    Open it once from Finder, then right-click its Dock tile -> "
          "Options -> Keep in Dock.")


if __name__ == "__main__":
    main()
